
```{r flow, echo = FALSE, cache = FALSE, include = FALSE, out.width = '80%', fig.align = "center", fig.cap = "(ref: flow), evaluate=FALSE"}
library(DiagrammeR)
library(tidyverse)
library(DiagrammeRsvg)
library(rsvg)
library(here)

#In the final chapter, I present a summary of the conclusions of this thesis.

graph<-grViz("digraph flowchart {
      # node definitions with substituted label text
      node [fontname = Helvetica, shape = rectangle, fontsize=12]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
        tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8']

      # edge definitions with the node IDs
    #  tab1 -> tab2;
     # tab2 -> tab3;
      #tab2 -> tab4 -> tab5

      tab1 -> tab2;
        
        tab1 -> tab3;
        tab1 -> tab4
        tab3 -> tab5
tab2 -> tab5
tab4 -> tab5
tab5 -> tab6
tab6 -> tab7
tab7 -> tab8
     
      }
      }

      [1]: 'Chapter 1: Introduction'
      [2]: 'Chapter 2: Literature review'
      [3]: 'Chapter 3: Background and methods'
      [4]: 'Chapter 4: Sedimentology and stratigraphy \\n of Sanamere Lagoon'
      [5]: 'Chapter 5: The development of a radiocarbon chronology for \\n Sanamere Lagoon using multiple organic fractions \\n Aim I '
      [6]: 'Chapter 6: 33,000 years of palaeohydrological record from \\n Sanamere Lagoon, northeastern tropical savannas of Australia \\n Aim II'
      [7]: 'Chapter 7: Vegetation and fire dynamics of the \\n northern Cape York tropical savannas over the last 33,000 years \\n Aim III'
      [8]: 'Chapter 8: Discussion and further research'
      ")

graph<-grViz("digraph {
      # node definitions with substituted label text
      node [fontname = Helvetica, shape = rectangle, fontsize=24]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
    tab6 [label = '@@6']
tab7 [label = '@@7']
      tab8 [label = '@@8']
tab9 [label = '@@9']
tab10 [label = '@@10']
    
      # edge definitions with the node IDs

      tab1 -> tab2;
        
        tab2 -> tab3;

tab3 -> tab4;

tab4 -> tab5;

tab5 -> tab6;

tab6 -> tab7;

tab7 -> tab8;

tab8 -> tab9;

tab9 -> tab10


   

     
      }
      }

      [1]: '1. Acquire data'
      [2]: 'Radiocarbon dating \\n Phytolith counting \\n Diatom counting \\n Elemental abundance \\n Isotopic abundance \\n Grain size \\n Pyrogenic carbon'
      [3]: 'From sediment core'
    [4]: '>3,000 observations from 35 variables'
      [5]: '2. Data cleaning and wrangling'
      [6]: 'Missing values \\n data resolution \\n diverse formats \\n ensure data quality'
      [7]: '3. Data mining and analysis'
      [8]: '4. Model implementation'
[9]: '5. Model evaluation'
[10]: '6. Dissemination'
      ")


#grViz(graph) %>%
 #   export_svg %>% charToRaw %>% rsvg_png("graph.png")

#export_graph(graph,
#file_name = "flow.png",
#file_type = "png")
export_svg(graph) %>%
charToRaw () %>% rsvg () %>% png::writePNG(here("short overview","graphs_2.png"))

```


```{r flow, echo = FALSE, cache = FALSE, include = FALSE, out.width = '80%', fig.align = "center", fig.cap = "(ref: flow), evaluate=FALSE"}
graph<-grViz("digraph {
      # node definitions with substituted label text
      node [fontname = Helvetica, shape = rectangle, fontsize=24]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
        tab6 [label = '@@6']
      tab7 [label = '@@7']
    
      # edge definitions with the node IDs
    #  tab1 -> tab2;
     # tab2 -> tab3;
      #tab2 -> tab4 -> tab5

      tab1 -> tab2;
        
        tab2 -> tab3;

tab 3 -> tab4

tab4 -> tab5
   

     
      }
      }

      [1]: '1. Acquire data'
      [2]: 'Radiocarbon dating \\n Phytolith counting \\n Diatom counting \\n Elemental abundance \\n Isotopic abundance \\n Grain size \\n Pyrogenic carbon '
      [3]: 'From sediment core'
      [4]: '2. Data cleaning and wrangling'
      [5]: 'Missing values \\n data resolution \\n diverse formats \\n ensure data quality'
      ")


#grViz(graph) %>%
 #   export_svg %>% charToRaw %>% rsvg_png("graph.png")

#export_graph(graph,
#file_name = "flow.png",
#file_type = "png")
export_svg(graph) %>%
charToRaw () %>% rsvg () %>% png::writePNG(here("short overview","graphs_2.png"))
```